# Generated by Django 4.1 on 2022-08-30 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Agency name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Agency description')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Agency rating')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Tour price from agency')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Tour discount from agency')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agency',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Place name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Place description')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Agency rating')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Excursion price from customer')),
            ],
            options={
                'verbose_name': 'Excursion',
                'verbose_name_plural': 'Excursions',
                'db_table': 'excursion',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hotel name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Hotel description')),
                ('stars', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Hotel stars')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Hotel rating')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Hotel price for week')),
                ('room_types', models.CharField(choices=[('APARTMENT', 'Apartment'), ('BALCONY', 'Balcony'), ('CONNECTED_ROOMS', 'Connected rooms'), ('BUSINESS', 'Business'), ('DELUXE', 'Deluxe'), ('DUPLEX', 'Duplex'), ('FAMILY_ROOM', 'Family room'), ('FAMILY_STUDIO', 'Family studio'), ('HONEYMOON', 'Honeymoon'), ('PRESIDENT', 'President'), ('STANDARD', 'Standard'), ('STUDIO', 'Studio'), ('SUPERIOR', 'Superior')], default='STANDARD', max_length=255, verbose_name='Hotel room choices')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotel',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Hotel photo description')),
                ('photo', models.ImageField(upload_to='hotels/', verbose_name='Hotel photo')),
            ],
            options={
                'verbose_name': 'HotelPhoto',
                'verbose_name_plural': 'HotelPhotos',
                'db_table': 'hotel_photo',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InterestingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Place name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Place description')),
                ('history', models.TextField(blank=True, max_length=10000, verbose_name='Place history')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Agency rating')),
                ('excursions', models.ManyToManyField(related_name='place_excursions', to='tourism.excursion', verbose_name='Place excursions')),
            ],
            options={
                'verbose_name': 'InterestingPlace',
                'verbose_name_plural': 'InterestingPlaces',
                'db_table': 'interesting_place',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Place photo description')),
                ('photo', models.ImageField(upload_to='places/', verbose_name='Places photo')),
            ],
            options={
                'verbose_name': 'PlacePhoto',
                'verbose_name_plural': 'PlacePhotos',
                'db_table': 'place_photo',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tour name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Tour description')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Agency rating')),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_agency', to='tourism.agency', verbose_name='Tour agency')),
                ('places', models.ManyToManyField(related_name='list_of_places', to='tourism.interestingplace', verbose_name='List of interesting places')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tour',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Travel name')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Travel description')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Travel rating')),
                ('travel_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_hotel', to='tourism.hotel', verbose_name='Travel hotel')),
                ('travel_tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_tour', to='tourism.tour', verbose_name='Travel tour')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travels',
                'db_table': 'travel',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='interestingplace',
            name='place_photo',
            field=models.ManyToManyField(related_name='place_photo', to='tourism.placephoto', verbose_name='Place photo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_photo',
            field=models.ManyToManyField(related_name='hotel_photo', to='tourism.hotelphoto', verbose_name='Hotel photo'),
        ),
    ]
