# Generated by Django 4.1 on 2022-08-30 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursion_owner', to=settings.AUTH_USER_MODEL, verbose_name='Excursion owner'),
        ),
    ]
