# Generated by Django 4.1 on 2022-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('TOURS_OF_THE_DAY', 'Tours of the day'), ('HOT_TOURS', 'Hot tours'), ('EXCLUSIVE_TOURS', 'Exclusive tours'), ('BUS_TOURS', 'Bus tours'), ('CRUISES', 'Cruises'), ('FLIGHTS', 'Flights')], default='FLIGHTS', max_length=255, verbose_name='Tour type'),
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Country name')),
                ('language', models.CharField(blank=True, max_length=255, verbose_name='Country language')),
                ('description', models.TextField(blank=True, max_length=10000, verbose_name='Country description')),
                ('visa', models.TextField(blank=True, max_length=10000, verbose_name='Country visa')),
                ('insurance', models.TextField(blank=True, max_length=10000, verbose_name='Country insurance')),
                ('mem', models.TextField(blank=True, max_length=10000, verbose_name='Tourist mem list')),
                ('transfer', models.TextField(blank=True, max_length=10000, verbose_name='Country transfer')),
                ('support', models.CharField(blank=True, max_length=255, verbose_name='Country support')),
                ('excursions', models.ManyToManyField(related_name='country_excursions', to='tourism.excursion', verbose_name='Country excursions')),
                ('travels', models.ManyToManyField(related_name='country_travels', to='tourism.travel', verbose_name='Country travels')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ('id',),
            },
        ),
    ]
