APARTMENT = 'APARTMENT'
BALCONY = 'BALCONY'
CONNECTED_ROOMS = 'CONNECTED_ROOMS'
BUSINESS = 'BUSINESS'
DELUXE = 'DELUXE'
DUPLEX = 'DUPLEX'
FAMILY_ROOM = 'FAMILY_ROOM'
FAMILY_STUDIO = 'FAMILY_STUDIO'
HONEYMOON = 'HONEYMOON'
PRESIDENT = 'PRESIDENT'
STANDARD = 'STANDARD'
STUDIO = 'STUDIO'
SUPERIOR = 'SUPERIOR'

ROOM_CHOICES = [
    (APARTMENT, 'Apartment'),
    (BALCONY, 'Balcony'),
    (CONNECTED_ROOMS, 'Connected rooms'),
    (BUSINESS, 'Business'),
    (DELUXE, 'Deluxe'),
    (DUPLEX, 'Duplex'),
    (FAMILY_ROOM, 'Family room'),
    (FAMILY_STUDIO, 'Family studio'),
    (HONEYMOON, 'Honeymoon'),
    (PRESIDENT, 'President'),
    (STANDARD, 'Standard'),
    (STUDIO, 'Studio'),
    (SUPERIOR, 'Superior'),
]

TOURS_OF_THE_DAY = 'TOURS_OF_THE_DAY'
HOT_TOURS = 'HOT_TOURS'
EXCLUSIVE_TOURS = 'EXCLUSIVE_TOURS'
BUS_TOURS = 'BUS_TOURS'
CRUISES = 'CRUISES'
FLIGHTS = 'FLIGHTS'

TOURS_CHOICES = [
    (TOURS_OF_THE_DAY, 'Tours of the day'),
    (HOT_TOURS, 'Hot tours'),
    (EXCLUSIVE_TOURS, 'Exclusive tours'),
    (BUS_TOURS, 'Bus tours'),
    (CRUISES, 'Cruises'),
    (FLIGHTS, 'Flights'),
]
